### ISSUE TITLE
Splitting es6 arrow functions from  '=>' to  '= >' with no way to turn off/change

### ISSUE THREAD

**Issue by trevordmiller** [wearefractal/gulp-beautify#17]
My ES6 arrow functions `=>` are being turned into `= >` which breaks JS parsing; I don't see a way to turn off or change the `=` space settings? `js-beautify` solved this problem: https://github.com/beautify-web/js-beautify/issues/402

Thank you

**Comment by contra** [comment]
We just wrap the node-beautify module, you should open this there

**Comment by contra** [comment]
I'm open to switching to use js-beautify under the hood, it seems better maintained
